Create API allowing select synchronization strategy
membraneframework/membrane_timestamp_queue pull request #5
Opened 2024-04-18 09:52 UTC by FelonEkonom

2024-04-22 12:47 UTC, mat-hek requested changes

2024-04-22 12:47 UTC, mat-hek commented on lib/membrane/timestamp_queue.ex
>              awaiting_pads: [Pad.ref()],
let's add a comment that it contains at most one element

2024-04-22 12:47 UTC, mat-hek commented on lib/membrane/timestamp_queue.ex
> +        push_pad_on_heap(timestamp_queue, pad_ref, priority)
As we spoke, let's move that to push_buffer

2024-04-22 12:47 UTC, mat-hek commented on lib/membrane/timestamp_queue.ex
> +              valid_offset
let's handle the first buffer separately

2024-04-23 07:55 UTC, mat-hek commented on mix.exs
> +      {:heap, "~> 2.0"},
why this?

2024-04-23 09:18 UTC, FelonEkonom commented on mix.exs
> +      {:heap, "~> 2.0"},
Because `3.0` has weird licence

2024-04-23 09:19 UTC, mat-hek approved these changes

2024-04-23 09:19 UTC, merged